// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---------------- //
// DmxInputInverted //
// ---------------- //

#define DmxInputInverted_wrap_target 5
#define DmxInputInverted_wrap 12

static const uint16_t DmxInputInverted_program_instructions[] = {
    0xe03d, //  0: set    x, 29                      
    0x00c3, //  1: jmp    pin, 3                     
    0x0000, //  2: jmp    0                          
    0x0041, //  3: jmp    x--, 1                     
    0x2020, //  4: wait   0 pin, 0                   
            //     .wrap_target
    0x20a0, //  5: wait   1 pin, 0                   
    0xe427, //  6: set    x, 7                   [4] 
    0x4001, //  7: in     pins, 1                    
    0x0247, //  8: jmp    x--, 7                 [2] 
    0x2020, //  9: wait   0 pin, 0                   
    0xa0ce, // 10: mov    isr, !isr                  
    0x4078, // 11: in     null, 24                   
    0x8020, // 12: push   block                      
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program DmxInputInverted_program = {
    .instructions = DmxInputInverted_program_instructions,
    .length = 13,
    .origin = -1,
};

static inline pio_sm_config DmxInputInverted_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + DmxInputInverted_wrap_target, offset + DmxInputInverted_wrap);
    return c;
}
#endif

